name: dz6
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - beautifulsoup4
  - docutils
  - jinja2=3.1.4
  - wheel
  - fastai
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - opencv
  - ipykernel
  - jupyter
  - ipywidgets
  - pip
  - pip:
      - kagglehub
      - tensorflow
      - tensorflow-metal
      - torch --pre --extra-index-url https://download.pytorch.org/whl/nightly/cpu
      - torchvision --pre --extra-index-url https://download.pytorch.org/whl/nightly/cpu
      - torchaudio --pre --extra-index-url https://download.pytorch.org/whl/nightly/cpu
